batch_size: 1
num_workers: 4

ckpt_root: ../ckpts
resume_path: /path/ckpt/to/ckpt

model: GFL4

data_config:
  name: RELLIS_3D
  data_root: E:\dataset\RELLIS_3D\Rellis-3D-custom
  load_interval: 1
  num_test_samples: -1

  raw_cam_img_size: [1200, 1920]
  ratio: 3